/*
    Copyright 2023 Jesse Talavera-Greenberg

    melonDS DS is free software: you can redistribute it and/or modify it under
    the terms of the GNU General Public License as published by the Free
    Software Foundation, either version 3 of the License, or (at your option)
    any later version.

    melonDS DS is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
    FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with melonDS DS. If not, see http://www.gnu.org/licenses/.
*/

#ifndef MELONDS_DS_CONFIG_DEFINITIONS_TIME_HPP
#define MELONDS_DS_CONFIG_DEFINITIONS_TIME_HPP

#include <libretro.h>

#include "../constants.hpp"

#ifdef RELATIVE
#undef RELATIVE
#endif

namespace MelonDsDs::config::definitions {
    constexpr retro_core_option_v2_definition StartTimeMode {
        config::time::START_TIME_MODE,
        "Starting Time Mode",
        nullptr,
        "The initial time of the emulated console's internal clock.\n"
        "\n"
        "- Real: Start in sync with your device's clock.\n"
        "- Relative: Start in sync with your device's clock, "
        "plus or minus a specified offset. "
        "Will be constrained to dates that the DS can represent.\n"
        "- Absolute: Start at a specific date and time, regardless of your device's clock.\n"
        "\n"
        "All dates and times are in your local timezone. "
        "Changes take effect at next restart.",
        nullptr,
        config::time::CATEGORY,
        {
            {values::REAL, "Real"},
            {values::RELATIVE_TIME, "Relative"},
            {values::ABSOLUTE_TIME, "Absolute"},
            {nullptr, nullptr},
        },
        values::REAL
    };

    constexpr retro_core_option_v2_definition RelativeYearOffset {
        config::time::RELATIVE_YEAR_OFFSET,
        "Starting Time Offset (Years)",
        nullptr,
        "The number of years to offset the starting time by. "
        "Only used when Starting Time Mode is Relative. "
        "Changes take effect at next restart.",
        nullptr,
        config::time::CATEGORY,
        {
            {"-20", "-20 years"},
            {"-19", "-19 years"},
            {"-18", "-18 years"},
            {"-17", "-17 years"},
            {"-16", "-16 years"},
            {"-15", "-15 years"},
            {"-14", "-14 years"},
            {"-13", "-13 years"},
            {"-12", "-12 years"},
            {"-11", "-11 years"},
            {"-10", "-10 years"},
            {"-9", "-9 years"},
            {"-8", "-8 years"},
            {"-7", "-7 years"},
            {"-6", "-6 years"},
            {"-5", "-5 years"},
            {"-4", "-4 years"},
            {"-3", "-3 years"},
            {"-2", "-2 years"},
            {"-1", "-1 year"},
            {"0", "None"},
            {"1", "+1 year"},
            {"2", "+2 years"},
            {"3", "+3 years"},
            {"4", "+4 years"},
            {"5", "+5 years"},
            {"6", "+6 years"},
            {"7", "+7 years"},
            {"8", "+8 years"},
            {"9", "+9 years"},
            {"10", "+10 years"},
            {"11", "+11 years"},
            {"12", "+12 years"},
            {"13", "+13 years"},
            {"14", "+14 years"},
            {"15", "+15 years"},
            {"16", "+16 years"},
            {"17", "+17 years"},
            {"18", "+18 years"},
            {"19", "+19 years"},
            {"20", "+20 years"},
            {nullptr, nullptr},
        },
        "0"
    };

    constexpr retro_core_option_v2_definition RelativeDayOffset {
        config::time::RELATIVE_DAY_OFFSET,
        "Starting Offset (Days)",
        nullptr,
        "The number of days to offset the starting time by. "
        "Only used when Starting Time Mode is Relative. "
        "Changes take effect at next restart.",
        nullptr,
        config::time::CATEGORY,
        {
            {"-364", "-364 days"},
            {"-180", "-180 days"},
            {"-150", "-150 days"},
            {"-120", "-120 days"},
            {"-90", "-90 days"},
            {"-60", "-60 days"},
            {"-30", "-30 days"},
            {"-14", "-14 days"},
            {"-13", "-13 days"},
            {"-12", "-12 days"},
            {"-11", "-11 days"},
            {"-10", "-10 days"},
            {"-9", "-9 days"},
            {"-8", "-8 days"},
            {"-7", "-7 days"},
            {"-6", "-6 days"},
            {"-5", "-5 days"},
            {"-4", "-4 days"},
            {"-3", "-3 days"},
            {"-2", "-2 days"},
            {"-1", "-1 day"},
            {"0", "None"},
            {"1", "+1 day"},
            {"2", "+2 days"},
            {"3", "+3 days"},
            {"4", "+4 days"},
            {"5", "+5 days"},
            {"6", "+6 days"},
            {"7", "+7 days"},
            {"8", "+8 days"},
            {"9", "+9 days"},
            {"10", "+10 days"},
            {"11", "+11 days"},
            {"12", "+12 days"},
            {"13", "+13 days"},
            {"14", "+14 days"},
            {"30", "+30 days"},
            {"60", "+60 days"},
            {"90", "+90 days"},
            {"120", "+120 days"},
            {"150", "+150 days"},
            {"180", "+180 days"},
            {"364", "+364 days"},
            {nullptr, nullptr},
        },
        "0"
    };

    constexpr retro_core_option_v2_definition RelativeHourOffset {
        config::time::RELATIVE_HOUR_OFFSET,
        "Starting Offset (Hours)",
        nullptr,
        "The number of hours to offset the starting time by. "
        "Only used when Starting Time Mode is Relative. "
        "Changes take effect at next restart.",
        nullptr,
        config::time::CATEGORY,
        {
            {"-23", "-23 hours"},
            {"-22", "-22 hours"},
            {"-21", "-21 hours"},
            {"-20", "-20 hours"},
            {"-19", "-19 hours"},
            {"-18", "-18 hours"},
            {"-17", "-17 hours"},
            {"-16", "-16 hours"},
            {"-15", "-15 hours"},
            {"-14", "-14 hours"},
            {"-13", "-13 hours"},
            {"-12", "-12 hours"},
            {"-11", "-11 hours"},
            {"-10", "-10 hours"},
            {"-9", "-9 hours"},
            {"-8", "-8 hours"},
            {"-7", "-7 hours"},
            {"-6", "-6 hours"},
            {"-5", "-5 hours"},
            {"-4", "-4 hours"},
            {"-3", "-3 hours"},
            {"-2", "-2 hours"},
            {"-1", "-1 hour"},
            {"0", "None"},
            {"1", "+1 hour"},
            {"2", "+2 hours"},
            {"3", "+3 hours"},
            {"4", "+4 hours"},
            {"5", "+5 hours"},
            {"6", "+6 hours"},
            {"7", "+7 hours"},
            {"8", "+8 hours"},
            {"9", "+9 hours"},
            {"10", "+10 hours"},
            {"11", "+11 hours"},
            {"12", "+12 hours"},
            {"13", "+13 hours"},
            {"14", "+14 hours"},
            {"15", "+15 hours"},
            {"16", "+16 hours"},
            {"17", "+17 hours"},
            {"18", "+18 hours"},
            {"19", "+19 hours"},
            {"20", "+20 hours"},
            {"21", "+21 hours"},
            {"22", "+22 hours"},
            {"23", "+23 hours"},
            {nullptr, nullptr},
        },
        "0"
    };

    constexpr retro_core_option_v2_definition RelativeMinuteOffset {
        config::time::RELATIVE_MINUTE_OFFSET,
        "Starting Offset (Minutes)",
        nullptr,
        "The number of minutes to offset the starting time by. "
        "Only used when Starting Time Mode is Relative. "
        "Changes take effect at next restart.",
        nullptr,
        config::time::CATEGORY,
        {
            {"-59", "-59 minutes"},
            {"-58", "-58 minutes"},
            {"-57", "-57 minutes"},
            {"-56", "-56 minutes"},
            {"-55", "-55 minutes"},
            {"-54", "-54 minutes"},
            {"-53", "-53 minutes"},
            {"-52", "-52 minutes"},
            {"-51", "-51 minutes"},
            {"-50", "-50 minutes"},
            {"-49", "-49 minutes"},
            {"-48", "-48 minutes"},
            {"-47", "-47 minutes"},
            {"-46", "-46 minutes"},
            {"-45", "-45 minutes"},
            {"-44", "-44 minutes"},
            {"-43", "-43 minutes"},
            {"-42", "-42 minutes"},
            {"-41", "-41 minutes"},
            {"-40", "-40 minutes"},
            {"-39", "-39 minutes"},
            {"-38", "-38 minutes"},
            {"-37", "-37 minutes"},
            {"-36", "-36 minutes"},
            {"-35", "-35 minutes"},
            {"-34", "-34 minutes"},
            {"-33", "-33 minutes"},
            {"-32", "-32 minutes"},
            {"-31", "-31 minutes"},
            {"-30", "-30 minutes"},
            {"-29", "-29 minutes"},
            {"-28", "-28 minutes"},
            {"-27", "-27 minutes"},
            {"-26", "-26 minutes"},
            {"-25", "-25 minutes"},
            {"-24", "-24 minutes"},
            {"-23", "-23 minutes"},
            {"-22", "-22 minutes"},
            {"-21", "-21 minutes"},
            {"-20", "-20 minutes"},
            {"-19", "-19 minutes"},
            {"-18", "-18 minutes"},
            {"-17", "-17 minutes"},
            {"-16", "-16 minutes"},
            {"-15", "-15 minutes"},
            {"-14", "-14 minutes"},
            {"-13", "-13 minutes"},
            {"-12", "-12 minutes"},
            {"-11", "-11 minutes"},
            {"-10", "-10 minutes"},
            {"-9", "-9 minutes"},
            {"-8", "-8 minutes"},
            {"-7", "-7 minutes"},
            {"-6", "-6 minutes"},
            {"-5", "-5 minutes"},
            {"-4", "-4 minutes"},
            {"-3", "-3 minutes"},
            {"-2", "-2 minutes"},
            {"-1", "-1 minute"},
            {"0", "None"},
            {"1", "+1 minute"},
            {"2", "+2 minutes"},
            {"3", "+3 minutes"},
            {"4", "+4 minutes"},
            {"5", "+5 minutes"},
            {"6", "+6 minutes"},
            {"7", "+7 minutes"},
            {"8", "+8 minutes"},
            {"9", "+9 minutes"},
            {"10", "+10 minutes"},
            {"11", "+11 minutes"},
            {"12", "+12 minutes"},
            {"13", "+13 minutes"},
            {"14", "+14 minutes"},
            {"15", "+15 minutes"},
            {"16", "+16 minutes"},
            {"17", "+17 minutes"},
            {"18", "+18 minutes"},
            {"19", "+19 minutes"},
            {"20", "+20 minutes"},
            {"21", "+21 minutes"},
            {"22", "+22 minutes"},
            {"23", "+23 minutes"},
            {"24", "+24 minutes"},
            {"25", "+25 minutes"},
            {"26", "+26 minutes"},
            {"27", "+27 minutes"},
            {"28", "+28 minutes"},
            {"29", "+29 minutes"},
            {"30", "+30 minutes"},
            {"31", "+31 minutes"},
            {"32", "+32 minutes"},
            {"33", "+33 minutes"},
            {"34", "+34 minutes"},
            {"35", "+35 minutes"},
            {"36", "+36 minutes"},
            {"37", "+37 minutes"},
            {"38", "+38 minutes"},
            {"39", "+39 minutes"},
            {"40", "+40 minutes"},
            {"41", "+41 minutes"},
            {"42", "+42 minutes"},
            {"43", "+43 minutes"},
            {"44", "+44 minutes"},
            {"45", "+45 minutes"},
            {"46", "+46 minutes"},
            {"47", "+47 minutes"},
            {"48", "+48 minutes"},
            {"49", "+49 minutes"},
            {"50", "+50 minutes"},
            {"51", "+51 minutes"},
            {"52", "+52 minutes"},
            {"53", "+53 minutes"},
            {"54", "+54 minutes"},
            {"55", "+55 minutes"},
            {"56", "+56 minutes"},
            {"57", "+57 minutes"},
            {"58", "+58 minutes"},
            {"59", "+59 minutes"},
            {nullptr, nullptr},
        },
        "0"
    };

    constexpr retro_core_option_v2_definition AbsoluteYear {
        config::time::ABSOLUTE_YEAR,
        "Starting Year",
        nullptr,
        "The initial year to use when Starting Time Mode is Absolute. "
        "Changes take effect at next restart.",
        nullptr,
        config::time::CATEGORY,
        {
            {"2000", nullptr},
            {"2001", nullptr},
            {"2002", nullptr},
            {"2003", nullptr},
            {"2004", nullptr},
            {"2005", nullptr},
            {"2006", nullptr},
            {"2007", nullptr},
            {"2008", nullptr},
            {"2009", nullptr},
            {"2010", nullptr},
            {"2011", nullptr},
            {"2012", nullptr},
            {"2013", nullptr},
            {"2014", nullptr},
            {"2015", nullptr},
            {"2016", nullptr},
            {"2017", nullptr},
            {"2018", nullptr},
            {"2019", nullptr},
            {"2020", nullptr},
            {"2021", nullptr},
            {"2022", nullptr},
            {"2023", nullptr},
            {"2024", nullptr},
            {"2025", nullptr},
            {"2026", nullptr},
            {"2027", nullptr},
            {"2028", nullptr},
            {"2029", nullptr},
            {"2030", nullptr},
            {"2031", nullptr},
            {"2032", nullptr},
            {"2033", nullptr},
            {"2034", nullptr},
            {"2035", nullptr},
            {"2036", nullptr},
            {"2037", nullptr},
            {"2038", nullptr},
            {"2039", nullptr},
            {"2040", nullptr},
            {"2041", nullptr},
            {"2042", nullptr},
            {"2043", nullptr},
            {"2044", nullptr},
            {"2045", nullptr},
            {"2046", nullptr},
            {"2047", nullptr},
            {"2048", nullptr},
            {"2049", nullptr},
            {"2050", nullptr},
            {"2051", nullptr},
            {"2052", nullptr},
            {"2053", nullptr},
            {"2054", nullptr},
            {"2055", nullptr},
            {"2056", nullptr},
            {"2057", nullptr},
            {"2058", nullptr},
            {"2059", nullptr},
            {"2060", nullptr},
            {"2061", nullptr},
            {"2062", nullptr},
            {"2063", nullptr},
            {"2064", nullptr},
            {"2065", nullptr},
            {"2066", nullptr},
            {"2067", nullptr},
            {"2068", nullptr},
            {"2069", nullptr},
            {"2070", nullptr},
            {"2071", nullptr},
            {"2072", nullptr},
            {"2073", nullptr},
            {"2074", nullptr},
            {"2075", nullptr},
            {"2076", nullptr},
            {"2077", nullptr},
            {"2078", nullptr},
            {"2079", nullptr},
            {"2080", nullptr},
            {"2081", nullptr},
            {"2082", nullptr},
            {"2083", nullptr},
            {"2084", nullptr},
            {"2085", nullptr},
            {"2086", nullptr},
            {"2087", nullptr},
            {"2088", nullptr},
            {"2089", nullptr},
            {"2090", nullptr},
            {"2091", nullptr},
            {"2092", nullptr},
            {"2093", nullptr},
            {"2094", nullptr},
            {"2095", nullptr},
            {"2096", nullptr},
            {"2097", nullptr},
            {"2098", nullptr},
            {"2099", nullptr},
            {"2100", nullptr},
            {nullptr, nullptr},
        },
        "2004",
    };

    constexpr retro_core_option_v2_definition AbsoluteMonth {
        config::time::ABSOLUTE_MONTH,
        "Starting Month",
        nullptr,
        "The initial month to use when Starting Time Mode is Absolute. "
        "Changes take effect at next restart.",
        nullptr,
        config::time::CATEGORY,
        {
            {"1", "January"},
            {"2", "February"},
            {"3", "March"},
            {"4", "April"},
            {"5", "May"},
            {"6", "June"},
            {"7", "July"},
            {"8", "August"},
            {"9", "September"},
            {"10", "October"},
            {"11", "November"},
            {"12", "December"},
            {nullptr, nullptr},
        },
        "1",
    };

    constexpr retro_core_option_v2_definition AbsoluteDay {
        config::time::ABSOLUTE_DAY,
        "Starting Month",
        nullptr,
        "The initial day of the month to use when Starting Time Mode is Absolute. "
        "Days that extend past the end of a month will roll over to the next (e.g. April 31st will become May 1st). "
        "Changes take effect at next restart.",
        nullptr,
        config::time::CATEGORY,
        {
            {"1", "1st"},
            {"2", "2nd"},
            {"3", "3rd"},
            {"4", "4th"},
            {"5", "5th"},
            {"6", "6th"},
            {"7", "7th"},
            {"8", "8th"},
            {"9", "9th"},
            {"10", "10th"},
            {"11", "11th"},
            {"12", "12th"},
            {"13", "13th"},
            {"14", "14th"},
            {"15", "15th"},
            {"16", "16th"},
            {"17", "17th"},
            {"18", "18th"},
            {"19", "19th"},
            {"20", "20th"},
            {"21", "21st"},
            {"22", "22nd"},
            {"23", "23rd"},
            {"24", "24th"},
            {"25", "25th"},
            {"26", "26th"},
            {"27", "27th"},
            {"28", "28th"},
            {"29", "29th"},
            {"30", "30th"},
            {"31", "31st"},
            {nullptr, nullptr},
        },
        "1",
    };

    constexpr retro_core_option_v2_definition AbsoluteHour {
        config::time::ABSOLUTE_HOUR,
        "Starting Hour",
        nullptr,
        "The initial hour to use when Starting Time Mode is Absolute. "
        "Changes take effect at next restart.",
        nullptr,
        config::time::CATEGORY,
        {
            {"0", "12 AM"},
            {"1", "1 AM"},
            {"2", "2 AM"},
            {"3", "3 AM"},
            {"4", "4 AM"},
            {"5", "5 AM"},
            {"6", "6 AM"},
            {"7", "7 AM"},
            {"8", "8 AM"},
            {"9", "9 AM"},
            {"10", "10 AM"},
            {"11", "11 AM"},
            {"12", "12 PM"},
            {"13", "1 PM"},
            {"14", "2 PM"},
            {"15", "3 PM"},
            {"16", "4 PM"},
            {"17", "5 PM"},
            {"18", "6 PM"},
            {"19", "7 PM"},
            {"20", "8 PM"},
            {"21", "9 PM"},
            {"22", "10 PM"},
            {"23", "11 PM"},
            {nullptr, nullptr},
        },
        "0",
    };

    constexpr retro_core_option_v2_definition AbsoluteMinute {
        config::time::ABSOLUTE_MINUTE,
        "Starting Minute",
        nullptr,
        "The initial minute to use when Starting Time Mode is Absolute. "
        "Changes take effect at next restart.",
        nullptr,
        config::time::CATEGORY,
        {
            {"0", ":00"},
            {"1", ":01"},
            {"2", ":02"},
            {"3", ":03"},
            {"4", ":04"},
            {"5", ":05"},
            {"6", ":06"},
            {"7", ":07"},
            {"8", ":08"},
            {"9", ":09"},
            {"10", ":10"},
            {"11", ":11"},
            {"12", ":12"},
            {"13", ":13"},
            {"14", ":14"},
            {"15", ":15"},
            {"16", ":16"},
            {"17", ":17"},
            {"18", ":18"},
            {"19", ":19"},
            {"20", ":20"},
            {"21", ":21"},
            {"22", ":22"},
            {"23", ":23"},
            {"24", ":24"},
            {"25", ":25"},
            {"26", ":26"},
            {"27", ":27"},
            {"28", ":28"},
            {"29", ":29"},
            {"30", ":30"},
            {"31", ":31"},
            {"32", ":32"},
            {"33", ":33"},
            {"34", ":34"},
            {"35", ":35"},
            {"36", ":36"},
            {"37", ":37"},
            {"38", ":38"},
            {"39", ":39"},
            {"40", ":40"},
            {"41", ":41"},
            {"42", ":42"},
            {"43", ":43"},
            {"44", ":44"},
            {"45", ":45"},
            {"46", ":46"},
            {"47", ":47"},
            {"48", ":48"},
            {"49", ":49"},
            {"50", ":50"},
            {"51", ":51"},
            {"52", ":52"},
            {"53", ":53"},
            {"54", ":54"},
            {"55", ":55"},
            {"56", ":56"},
            {"57", ":57"},
            {"58", ":58"},
            {"59", ":59"},
            {nullptr, nullptr},
        },
        "0",
    };
}

#endif //MELONDS_DS_CONFIG_DEFINITIONS_TIME_HPP
